sudo: false
language: python
python:
  - "3.6"

env:
  global:
    - VER_DTOOLS=1

script:
  - make -C dtools
  - find dtools

deploy:
  provider: releases
  skip_cleanup: true
  file:
    - "dtools/kk_dtools-${VER_DTOOLS}-py3-none-any.whl"
  on:
    tags: true
  api_key:
    secure: "O1GLtDe/KXGfRrPn23Ml8vuCe6Tt0+vK1LPyw1b5U6cVJBlobUHIgmDMvD7bKdLBE7xmDCGrjGipyXkF/UyWl14PCs49o/mYKRdxwYyBL/M54wYMP/e44xpepH+Jm16bjLUQTYbE9LIQGJZqOAzKU/3Ru9h+CGEYLgFFrE+XVgtzIJPN0Od9n3o8rPu1GC0Uaxv4tlis2re9hX61nPQF3EhWsdaDc6IFko6a+4Q+B07qs9o+5L8pqzLwEczUsA28Oq1UPNyGbXTnhq5gOwbV2zdKGemLsqQb2XdA1V2OSL/5sqx5XMy6ssakBWa4qmrMIxJ055n1T3zvIpzInLQbLPJq1KM7E5cXL7kezvHPVbhjoD+r6ABo1AbjvGNNI9tr0FYvGKcUJmjWp4IwHJiar1e3Jd3pxO9sYPP65sn2p8DP4i15Q+8QBEI7f5Lv00DNZUwK300bGeSzXCf4hMjcv+tu11fvvg1mFhPfRCL8AIESrnjXvfghAL5WLDNVK7LhRNr5y8k1tI8CHq0y/HYOjAgubmMYGPnj1nl8fIihz0KuvoWCbhOPfXACiW/EaVcChkxBQcnYn9Suzm1DtZIKbi92rhuVMTKTUPfP0rPgm6GNVa4UABxCnJoe834R1oGZlb5wj+G0DrpdWVzuKA+Rla9J8lW8cRBK7kKDOn/48nQ="

