sudo: false
language: python
python:
  - "3.6"

env:
  global:
    - VER_DTOOLS=1

script:
  - make -C dtools
  - find dtools

deploy:
  provider: releases
  skip_cleanup: true
  file:
    - "dtools/kk_dtools-${VER_DTOOLS}-py3-none-any.whl"
  on:
    tags: true
  api_key:
    secure: "Q2KXb7XCONRil8Aix+5t0i/BDY9fO080ZXZgBCZ1Ar2A0D5Sqfvg7m9hgOOd1fAwDMDJsMWrinVXbaBkpJHhcZu9P6GuXYpihMI/BMWDJbGeOzFWUDJb3zZCNwt/KlmiS0fvNa462faKsbobYCP9KPVO0N8O0BDjTr29oIVvG17bGVhsS900/4bBHGbd/urIruO8gs6Hc16kZl71PXsjuhPowDCefPS+/tifcg3q727AhlUYvvgDr8CrWYEmlwnnV6pzfTzINHH2XYgHpK1aB/werUp+c/HTQ8cGRM+K0XSb47CXuGSk2hypGdECws7PcK3DG7KiYwoYVntcCyUz7TcXdJ+G7rBy+EuBVQYmsXlTJAb18diVHwINMbE15R/yOraoV2K6+iK7qg+Rw9e4yZ+3RuemLeujv59Xk8ER0pfoOxlp1cBEL+FIzXsQKr2ghMYGxpktXyeSXbhWakIsKqwpEihbrgAORFHa2wmzb+721GHdgMp30OYnHF7Wt80b+oKST/ofwilylUxGvXVJU4cCN7rlHqTc7tCJA5L7n85TC9xFnV+HDSLIiLEvp7bE27pLD8zUkj8ovZHzfClf1vB2B7RCwe713Vrpplc/rY51SbNrQhwK4+dvC8pnzZCxTg7gmiaI2oNnOqMwuM4Vb6/OUw+cII3x69CRc7JpAK0="

