apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kk-nb-home
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
