name: CI

on: [push]

env:
  ORG: opendatacube
  IMAGE: geobase
  ghref: ${{ github.ref }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create env file
      run: |
        branch="${GITHUB_REF/refs\/heads\//}"
        TAG="${branch/master/latest}"
        BTAG="_build_cache_${branch}"
        BTAG="${BTAG/_master//}"

        cat > .env <<EOF
        branch=${branch}
        TAG=${TAG}
        BTAG=${BTAG}
        stage1="${ORG}/${IMAGE}:${BTAG}"
        stage2="${ORG}/${IMAGE}:${TAG}"
        EOF

    - name: Check env file
      run: |
        source .env
        echo "Stage1: >$stage1<"
        echo "Stage2: >$stage2<"


    - name: Run a multi-line script
      run: |
        echo "ENV TEST: ${ORG}/${IMAGE}:${TAG}"
        echo "ghref-env   : ${ghref}"
        echo "ghref-direct: ${{ github.ref }}"
        env | grep "GITHUB_"
        echo "${{ matrix.org }}/${{ matrix.image }}:${TAG}"
        cat > .env <<EOF
        FOO="message from prev step ${TAG}"
        EOF

      env:
        TAG: 1.3.4-fake

    - name: Run a multi-line script
      run: |
        source .env
        echo "foo: <${FOO}>"
