name: CI

on: [push]

env:
  ORG: opendatacube
  IMAGE: geobase
  ghref: ${{ github.ref }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        echo "ENV TEST: ${ORG}/${IMAGE}:${TAG}"
        echo "ghref-env   : ${ghref}"
        echo "ghref-direct: ${{ github.ref }}"
        env | grep "GITHUB_"
        echo "${{ matrix.org }}/${{ matrix.image }}:${TAG}"
        export FOO="message from prev step ${TAG}"
        cat > .env <<EOF
        FOO="message from prev step ${TAG}"
        EOF

      env:
        TAG: 1.3.4-fake

    - name: Run a multi-line script
      run: |
        echo "foo: <${FOO}>"
        env
        source .env
        echo "foo: <${FOO}>"
