name: CI

on: [push]

env:
  ORG: opendatacube
  IMAGE: geobase
  bb: ${ORG}/${IMAGE}
  ghref: ${{ github.ref }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo "ENV TEST: ${ORG}/${IMAGE}:${TAG}"
        echo "ENV TEST2: ${bb}:${TAG}"
        echo "ghref: ${ghref}"
        env

      env:
        TAG: 1.3.4-fake
